env:
  browser: true
  es6: true
  jest/globals: true
extends:
  - 'eslint:recommended'
  - 'plugin:vue/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2020
  sourceType: module
parser: vue-eslint-parser
plugins:
  - jest
  - vue
rules:
  "no-var": "error"
  "semi": "error"
  "indent": "error"
  "no-multi-spaces": "error"
  "space-in-parens": "error"
  "no-multiple-empty-lines": "error"
  "prefer-const": "error"
  "no-use-before-define": "error"
  "no-trailing-spaces": ["error", { "skipBlankLines": true, "ignoreComments": true }]
