inherit_gem:
  bixby: bixby_default.yml

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4

  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'bin/*'
    - 'config/deploy.rb'
    - 'config/initializers/blacklight_url_helper_behavior.rb'
    - 'config/environments/**/*'
    - 'node_modules/**/*'

Style/StringLiterals:
   EnforcedStyle: double_quotes

RSpec/DescribeClass:
  Exclude:
    - 'spec/views/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/controllers/travel_requests_controller_spec.rb'
    - 'spec/controllers/absence_requests_controller_spec.rb'
    - 'spec/decorators/travel_request_decorator_spec.rb'
