inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'bin/*'
    - 'node_modules/**/*'

Layout/IndentationConsistency:
   Enabled: false

Layout/IndentationWidth:
   Enabled: false

Style/StringLiterals:
   EnforcedStyle: double_quotes

RSpec/DescribeClass:
  Exclude:
    - 'spec/views/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/tasks/approvals.rake'
    - 'config/routes.rb'
    - config/environments/development.rb
    - config/environments/production.rb
    - config/environments/staging.rb
