---
version: 2.1
orbs: 
  node: circleci/node@5.0.0
executors:
  approvals-executor:
    docker:
      - image: circleci/ruby:2.7.5-browsers
        environment:
          BUNDLER_VERSION: 2.0.1
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: approvals
          RAILS_ENV: test
      - image: postgres:10
        environment:
          POSTGRES_USER: approvals
          POSTGRES_DB: approvals_test
          POSTGRES_HOST_AUTH_METHOD: trust
    working_directory: ~/project

commands:
  setup-bundler:
    description: "Install correct version of bundler and load from cache or bundle install"
    steps:
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler

      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v

      # Restore bundle cache
      - restore_cache:
          keys:
            - approvals-bundle-v3-{{ checksum "Gemfile.lock" }}
            - approvals-bundle-v3-

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      # Store bundle cache
      - save_cache:
          key: approvals-bundle-v3-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
  setup-node:
    description: "Set up the correct version of node"
    steps:
      - run:
          name: Install python 2 (needed to compile node-sass)
          command: sudo apt-get install -y python2

      - node/install:
          install-yarn: true
          node-version: '12.22.5'

      - run:
          name: Which node?
          command: node -v

jobs:
  build:
    executor: approvals-executor
    steps:
      - attach_workspace:
          at: '~/project'
      - checkout
      - setup-bundler
      - setup-node

      # Only necessary if app uses webpacker or yarn in some other way
      - restore_cache:
          keys:
            - approvals-yarn-v1-{{ checksum "yarn.lock" }}
            - approvals-yarn-v1-

      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn

      # Store yarn / webpacker cache
      - save_cache:
          key: approvals-yarn-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - persist_to_workspace:
          root: '~/project'
          paths: '*'

  test:
    executor: approvals-executor
    steps:
      - attach_workspace:
          at: '~/project'
      - setup-bundler
      - setup-node

      # ensure we have psql which we need for db:schema:load
      - run: sudo apt-get update --allow-releaseinfo-change
      - run: sudo apt-get install -y postgresql-client || true

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: |
            bin/rails db:create
            bin/rails db:structure:load

      # Run yarn test
      - run:
          name: Run jest tests
          command: yarn test

      - run:
          name: Run webpacker
          command: bin/webpack

      # Run rspec with percy
      - run:
          name: Run rspec
          command: |
            yarn percy exec -- bundle exec rspec --tag \~no_ci --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec/results.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb")


      # Save test results for timing analysis
      - store_test_results:
          path: test_results

      - persist_to_workspace:
          root: '~/project'
          paths: '*'

  rubocop:
    executor: approvals-executor
    steps:
      - attach_workspace:
          at: '~/project'
      - setup-bundler
      - run: bundle exec rubocop

  coverage_report:
    executor: approvals-executor
    steps:
      - attach_workspace:
          at: '~/project'
      - run: gem install simplecov
      - run:
          name: Inspect coverage report
          command: |
            RAILS_ENV=test ruby ./scripts/report_coverage.rb
      - store_artifacts:
          path: ~/project/coverage
          destination: coverage

workflows:
  build_accept:
    jobs:
      - build
      - rubocop:
         requires:
          - build
      - test:
         requires:
          - build
      - coverage_report:
         requires:
          - test
