- building: Firestone Library
- building: East Asian Library # Frist Campus Center Rm 317
- building: Research Collections # Forrestal Campus
- building: Tech Services # 693 Alexander
  admin_assistant: bszwast
- building: Seeley Mudd Manuscript Library # Olden Street
- building: Peter Lewis Science Library # Washington Rd, & Ivy Ln., 105
- building: Stokes Library # Wallace Hall
- building: Engineering Library # Friend Center
- building: Marquand Library   # McCormick Hall
- building: Music   # McCormick Hall
- building: Architecture Library # Architecture Building
- building: PPPL (DOE-3073 Contract # Forrestal Campus
