41000:
  head_uid: ajarvis
  admin_assistant: 
    - esamios
    - jbakeman
    - ddreyer
41004:
  admin_assistant: 
    - nishc
    - ddreyer
41006:
  admin_assistant:
    - ddreyer
    - nishc
41014:
  admin_assistant: 
    - ddreyer
10001:
  head_uid: ibogus
  admin_assistant: 
    - francesj
41032:
  admin_assistant: 
    - rdunham
    - temanuel
    - ddreyer
41034:
  head_uid: hwcowles
  admin_assistant:
    - ddreyer
26700:
  head_uid: nataliae
  admin_assistant:
    - nishc
    - ddreyer
