41000:
  head_uid: ajarvis
  admin_assistant: 
    - jbakeman
41004:
  admin_assistant: 
    - newalkar
41006:
  admin_assistant:
    - nishc
41014:
  admin_assistant: 
    - ddreyer
10001:
  head_uid: ibogus
  admin_assistant: 
    - francesj
41032:
  admin_assistant: 
    - temanuel
41034:
  head_uid: hwcowles
  admin_assistant:
    - az6987
26700:
  head_uid: nataliae
  admin_assistant:
    - esamios
