41000:
  head_uid: ajarvis
  admin_assistant: 
    - esamios
    - jbakemaa
    - ddreyern
41004:
  admin_assistant: 
    - nishc
41006:
  admin_assistant:
    - ddreyer
41014:
  admin_assistant: 
    - ddreyer
10001:
  head_uid: ibogus
  admin_assistant: 
    - francesj
41032:
  admin_assistant: 
    - rdunham
    - temanuel
