- Access Conference
- American Institute for Conservation (AIC)
- American Library Association - Annual Conference (ALA)
- American Library Association - Midwinter Meeting (ALA)
- American Musicological Society (AMS)
- Art Libraries Society of North America - New York (ARLIS/NY)
- Art Libraries Society of North America (ARLIS/NA)
- Asbury Agile
- Association of College and Research Libraries - New York (ACRL/NY)
- Association of College and Research Libraries (ACRL)
- Blacklight Summit
- Code4Lib
- College Art Association - Annual Conference (CAA)
- Computers in Libraries
- Digital Library Foundation Forum (DLF)
- Documents Association of New Jersey (DANJ)
- DrupalCampNJ
- DrupalCon
- edUI
- European Library Automation Group (ELAG)
- Geo4LibCamp
- International Image Interoperability Framework (IIIF)
- International Association for Social Science Information Services and Technology (IASSIST)
- Ivies Plus Access Services Symposium
- Ivies Plus Discovery Day
- LAMDevConX (LDCX)
- Mid-Atlantic Regional Archives Conference (MARAC)
- Middle East Librarians Association (MELA)
- Middle East Studies Association (MESA)
- Modern Greek Studies Association (MGSA)
- Monirotama
- Music Library Association (MLA)
- New York Antiquarian Book Fair
- New Jersey Library Association (NJLA)
- OCLC Resource Sharing Conference
- Open Repositories (OR)
- Preservation and Archiving Special Interest Group (PASIG)
- Rare Books and Manuscripts Section Conference (RBMS)
- RubyConf
- Samvera Connect
- Site Visit
- Smashing Conference
- Society of American Archivists (SAA)
- Special Libraries Association (SLA)
- Wharton Research Data and Analytics Librarian Conference (WRDAL)
- Workshop